### PR TITLE
Created FAQ section

### LINKED ISSUE #61: [Feature Request]A FAQ section for the beginners with appropriate resources.
I think a FAQ section in this website is must hence I am working on it and would like you to assign me this task

### PR DESCRIPTION
**Pull request by Vijay-Gunwant**
This closes #61 
Screenshot (90)
Screenshot (91)
This is the screenshots of what i have build

### CODE REVIEW

**Comment by AdarshRawat1** [comment]
@s-dabral @Kamalkoranga @CodeTorso your suggestions on this.

**Comment by s-dabral** [comment]
I think that you can add FAQ button but it should open the regarding questions in a new tab as opening a side bar doesn't really fits with the UI of the website.   @AdarshRawat1 your thoughts on this?

**Comment by CodeTorso** [comment]
I understand @Vijay-Gunwant that you have put a lot of time writing JS code and all that to make this function. 

But just making a section for faq in the website that users can scroll to and putting that same JS work into CSS work would have been great.

So I believe you have two paths :

1 Either ditch all the JS and add the faq content into the webpage.

2 Or if you just believe that your idea is better, Then make it more appealing , style it do whatever you believe is right. 

Just make sure that it fits with the website theme.

Best of Luck 🤗🤗

**Comment by Vijay-Gunwant** [comment]
> I understand @Vijay-Gunwant that you have put a lot of time writing JS code and all that to make this function.
> 
> But just making a section for faq in the website that users can scroll to and putting that same JS work into CSS work would have been great.
> 
> So I believe you have two paths :
> 
> 1 Either ditch all the JS and add the faq content into the webpage.
> 
> 2 Or if you just believe that your idea is better, Then make it more appealing , style it do whatever you believe is right.
> 
> Just make sure that it fits with the website theme.
> 
> Best of Luck 🤗🤗

ohk i will try my best

**Pull request closed without merging**
