### PR TITLE
[BUG] Adding GitHub link on the project cards

### LINKED ISSUE #56: [BUG] Adding GitHub link on the project cards
**Describe the bug**
A hyperlink to repository of project hosted on GitHub.

### PR DESCRIPTION
**Pull request by Kamalkoranga**
Fixes #56

Changes: 
image

### CODE REVIEW

**Comment by AdarshRawat1** [comment]
@Kamalkoranga you can add a bit more consistency to the design. 
- aligning the GitHub link button at bottom (thus bringing them to same level)

**Comment by AdarshRawat1** [comment]
p.s. make sure to sync your branch with `main` branch to avoid merge conflicts.

**Comment by Kamalkoranga** [comment]
> @Kamalkoranga the design is looking great!! You can add a bit more consistency to the design.
> 
> * aligning the GitHub link button at bottom (thus bringing them to same level)

Okay... I got it

**Comment by Kamalkoranga** [comment]
> @Kamalkoranga the design is looking great!! You can add a bit more consistency to the design.
> 
> * aligning the GitHub link button at bottom (thus bringing them to same level)

@AdarshRawat1  Aligned GitHub Link.

image

**Comment by AdarshRawat1** [comment]
> image

Nice work @Kamalkoranga !!

**Review by Taejin101 — COMMENTED** [review]
Looks great... 
One suggestion is that it would be great if box shadow appears on hover, not disappear.

**Comment by Kamalkoranga** [comment]
> 
> > image
> 
> Nice work @Kamalkoranga !!
> 
> 

Thanks 😊

**Pull request merged**
