### PR TITLE
Added pop up telling user our email service is currently inactive

### PR DESCRIPTION
**Pull request by CodeTorso**
This PR serves for issue #25 

This PR only uses vanilla JS to tell the user that our email service is currently inactive but don't worry your message is saved with you for the time coming.

I will be changing css a little bit but please get this PR in for now. 

https://github.com/OpenCodeEra/OpenCodeEra/assets/129188028/abe4c2af-f296-44b3-a2c1-6ba40cb9ed77

### CODE REVIEW

**Comment by CodeTorso** [comment]
Took me 2-3 hours to get the JavaScript right. 

But due to some mistakes in github branching I had to merge this code with the upstream code.

Spent another 1 hour fixing JavaScript. Had to learn sqaushing commit in GitHub which took another 30 mins.

So overall it took me 4-5 hours to get here

**Comment by AdarshRawat1** [comment]
> So overall it took me 4-5 hours to get here

Kudos to your hardwork and dedication @CodeTorso

**Comment by AdarshRawat1** [comment]
@CodeTorso this explanation might be a bit overwhelming for users . 

# Suggestions ( feel free to discuss them before implementation)

- Pop up message - " this service is currently under maintenance" 

- include a button " more details"  where we can include this explanation( the one you provided) .

**Comment by CodeTorso** [comment]
We should actually say sorry we have not built our backend yet. 😄😄.

Anyways will probably look into that matters. Give me 2 hours. I will send you screenshots in the next PR.

**Comment by AdarshRawat1** [comment]
> We should actually say sorry we have not built our backend yet. 😄😄.

 I'm still waiting for that PR of mail functionality. 😅

**Pull request merged**
