### PR TITLE
minor changes in contact page + screenshots 

### PR DESCRIPTION
**Pull request by CodeTorso**
**Screenshots of all the changes**
<br>

- I tried using know more but did not see it look any better. In contrast shortening the content worked better than that.
  
Screenshot 2023-09-14 102345

<br><br>

- The about us section had some css issues I fixed that. 
- Also, the `img` element was taking too much space and the actual image was much smaller than that. Thus I had to use negative `margin`. 

Screenshot 2023-09-14 101603

<br><br>

- This was the most cluttered section. 
- The form section was leaking out of the div. 
- The color of paragraph just not right. Also the paragraph was just in a shape of rectangle. 
- The left section was greater in height than the right section. 
- Some flex properties were overridden by some other things. Fixed all that.

Screenshot 2023-09-14 101522

<br><br>

- The anchor links were just too bright and as soon as you hover over them they turned blue. 
- First I made their color less bright. and also added a 0.5s transition so that they slowly become blue.
- left arrow shows hovered link and the right one the normal state

Screenshot 2023-09-14 101045

<br><br>

- Added so that the text in button cannot be selected neither the images, links and first section text. 
- The form has different text selection color than the p and h2 text. h2 selection color is little bit darker than p.

Screenshot 2023-09-14 101007

<br><br>

- The input border now matches with the color of website. Earlier it was white
- The text selection color is different because I don't but the selected input text was impossible to see if we had blue text selection as other elements.
- Also now input text has better font.

Screenshot 2023-09-14 100731

<br><br>

- This is the transition of how the popup appears and disappears.
- You may notice that the contact section when clicked the submit button comes at the center of screen so that it is fully visible.

https://github.com/OpenCodeEra/OpenCodeEra/assets/129188028/6654ed46-3bab-4f3a-8af5-bd4306ff0e69

<br><br>

- I have also removed some repeated css
- Ensured that there is only 1 h1 in the page
- and yeah that's it.

<br><br>

- These changes are not entirely part of this PR
- This PR is 5 commits ahead of main branch. Thus you need to merge PR 
- #26 
- #27 
- #28 
- #29 
- #30

### CODE REVIEW

**Comment by CodeTorso** [comment]
@AdarshRawat1 Did you follow the order of PR. I mean first merged #26 then #27 like that

**Comment by AdarshRawat1** [comment]
> **Screenshots of all the changes**
> 
> * I tried using know more but did not see it look any better. In contrast shortening the content worked better than that.


@CodeTorso The changes you made are excellent. Thank you for the PR.

**Comment by CodeTorso** [comment]
> > **Screenshots of all the changes**
> > 
> > * I tried using know more but did not see it look any better. In contrast shortening the content worked better than that.
> 
> @CodeTorso The changes you made are excellent. Thank you for the PR.

Just contributing. I will be learning the backend soon. Hope to contribute much more in that.

**Comment by CodeTorso** [comment]
Don't know why the hell code ain't working. Give me some time. Like 2 hours

https://github.com/OpenCodeEra/OpenCodeEra/assets/129188028/57404a15-6e9f-4740-8b55-5fd6f0bc344d

**Comment by CodeTorso** [comment]
probably errors in some merges. That's why big companies only allow one issue at a time. Don't worry Give me some time to fix

**Comment by CodeTorso** [comment]
> > @AdarshRawat1 Did you follow the order of PR. I mean first merged #26 then #27 like that
> > @CodeTorso
> > I missed the order. I reverted all the changes and merged all other PRs (except #30 and #31).
> > Please resend this PR. (Keep the same description).

Don't worry. Just merge #33. It is like master PR.

**Comment by AdarshRawat1** [comment]
> Don't worry. Just merge #33. It is like master PR.

Sure

**Pull request merged**
