### PR TITLE
Improve FAQ Accordion Interaction for Enhanced User Experience #94

### LINKED ISSUE #94: [BUG 🐞] Improve FAQ Accordion Interaction for Enhanced User Experience
### Description

# Issue Title: Improve FAQ Accordion Interaction for Enhanced User Experience

## Issue Description:
I am eager to contribute and have created this issue to address a specific concern related to the FAQ accordion component. Currently, the accordion opens only when the small toggle button is clicked, which can impact user experience. I aim to enhance the interaction by making it possible to open the accordion by clicking on the question itself. Additionally, I intend to simplify the code for this feature.

## Proposed Changes:
My contributions to the project will include the following:
- Modify the FAQ accordion interaction to open when a user clicks on the question text.
- Ensure a simplified and clean code implementation for this interaction change.

## Rationale:
Improving the FAQ accordion interaction is essential for the following reasons:

### Enhanced Usability:
Allowing users to open the accordion by clicking on the question text provides a more intuitive and user-friendly experience.

### Code Simplification:
Simplifying the code ensures that the project remains maintainable and clean, contributing to its long-term health.

## Attachments 
image

## Additional Information (if available):
If there are specific guidelines or preferences regarding code simplification or interaction changes, please provide them to help ensure that the proposed changes align with the project's goals.

Please consider this issue as my commitment to contribute to the project by enhancing the FAQ accordion interaction for an improved user experience.

### PR DESCRIPTION
**Pull request by purnasth**
# Pull Request: Enhance FAQ Accordion Interaction and Optimize Data Handling

## Description
This pull request addresses issue #94, which aims to improve the FAQ accordion interaction for a better user experience. The primary goal is to enable users to open the accordion by clicking on the question text while simplifying the code for this feature.

## Changes Made
1. **FAQ Accordion Interaction Enhancement**: Modified the FAQ accordion interaction so that it opens when a user clicks on the question text. This adjustment offers a more intuitive and user-friendly experience.
2. **Code Simplification**: Refactored the codebase to ensure clean and maintainable code, which contributes to the long-term health of the project.

## Data Handling Process
To optimize data handling, I fetched the FAQ content from `faq.json`. Instead of creating different classes and attributes, I leveraged the built-in HTML `<details>` and `<summary>` elements. This approach streamlined the code and made it more efficient. The FAQ data is now easily manageable and can be updated in the `faq.json` file, maintaining a separation of content and presentation.

## Attachments

https://github.com/OpenCodeEra/OpenCodeEra/assets/107195487/f3cc2f08-2c2a-4922-8ba4-0402e8104b69

## Additional Notes
I'm committed to enhancing the project's user experience and code quality. If any further adjustments or specific guidelines are needed, please provide your feedback. Your input is highly valued.

Closes #94

### CODE REVIEW

**Review by Kamalkoranga — APPROVED** [review]
Hey @purnasth nice work ..... Keep contributing

**Comment by AdarshRawat1** [comment]
@purnasth please resolve the conflicts so that we can merge the PR.

**Comment by purnasth** [comment]
can you please explain what are the conflicts here?

**Comment by AdarshRawat1** [comment]
> Hello @AdarshRawat1! can you please explain what are the conflicts here?

The merge conflicts!!

**Comment by AdarshRawat1** [comment]
@purnasth are you planning to open another fresh PR ??

**Comment by purnasth** [comment]
No!

**Comment by AdarshRawat1** [comment]
Can I help you in anyway? @purnasth

**Pull request closed without merging**
