### PR TITLE
Created FAQ section

### LINKED ISSUE #61: [Feature Request]A FAQ section for the beginners with appropriate resources.
I think a FAQ section in this website is must hence I am working on it and would like you to assign me this task

### PR DESCRIPTION
**Pull request by Vijay-Gunwant**
This fixes #61 
@AdarshRawat1 @CodeTorso @s-dabral here is what i have updated
Screenshot (95)

### CODE REVIEW

**Comment by s-dabral** [comment]
Yes i believe this is good enough. Good work  @Vijay-Gunwant

**Comment by Vijay-Gunwant** [comment]
> Yes i believe this is good enough. Good work @Vijay-Gunwant

Thanks @s-dabral waiting for its merge

**Comment by CodeTorso** [comment]
by the way , @Vijay-Gunwant  which college you from ?

**Comment by Vijay-Gunwant** [comment]
> by the way , @Vijay-Gunwant which college you from ?

GEHU Haldwani

**Comment by AdarshRawat1** [comment]
looks great @Vijay-Gunwant 
The content can be improved (will open a new issue for it) .

**Pull request merged**
