### PR TITLE
fix the navbar issue and make it responsive

### PR DESCRIPTION
**Pull request by officialhemant511**
https://github.com/OpenCodeEra/OpenCodeEra/assets/120431671/086da90e-7c5e-4352-a441-b05f279a734f

navbar2
navbar
fix: #93 and also solve the overflow issue of text .....and also fix the menu bar issue now it will be responsive...

### CODE REVIEW

**Comment by AdarshRawat1** [comment]
@officialhemant511 please include the screenshot and screen recording of the responsiveness.

**Comment by officialhemant511** [comment]
bro here..? or where i pull request ....
please help me to figure out .. btw thanks 😊

**Comment by AdarshRawat1** [comment]
> bro here..? or where i pull request ....
> please help me to figure out .. btw thanks 😊

Add a comment in the PR itself.
You can easily send videos/ images in GitHub comments.
Just paste or import the recording in your comment.

**Comment by officialhemant511** [comment]
> > bro here..? or where i pull request ....
> > please help me to figure out .. btw thanks 😊
> 
> Add a comment in the PR itself. You can easily send videos/ images in GitHub comments. Just paste or import the recording in your comment.

bro can u pls check i think i done :)

**Pull request merged**
