### PR TITLE
added social media icons

### PR DESCRIPTION
**Pull request by bilalshaikh292**

### CODE REVIEW

**Comment by CodeTorso** [comment]
Did you really create the linkedIn for this ??

**Comment by bilalshaikh292** [comment]
No

**Comment by AdarshRawat1** [comment]
> Did you really create the linkedIn for this ??

Our LinkedIn page is currently in a dormant stage. However, we are excited to announce that we will soon be revamping it with the help of our upcoming volunteer team who will handle our social media activities. As we kickstart our projects, we anticipate our LinkedIn page to become a vibrant community where we share our progress and engage with our followers. 

@bilalshaikh292  LinkedIn page - 

https://www.linkedin.com/company/open-code-era/

**Comment by CodeTorso** [comment]
> > Did you really create the linkedIn for this ??
> 
> Our LinkedIn page is currently in a dormant stage. However, we will soon be revamping it with the help of our upcoming volunteer team who will handle our social media activities. As we kickstart our projects, we anticipate our LinkedIn page to become a vibrant community where we share our progress and engage with our followers.
> 
> @bilalshaikh292 LinkedIn page -
> 
> https://www.linkedin.com/company/open-code-era/

Wait... How serious is this project ??

**Comment by CodeTorso** [comment]
Good Work. So I can continue contributing to this project.

**Comment by AdarshRawat1** [comment]
> Good Work. So I can continue contributing to this project.

SUre you can continue to work on it.

**Comment by AdarshRawat1** [comment]
@bilalshaikh292 kindly resolve the merge conflicts.

**Comment by bilalshaikh292** [comment]
ok

**Comment by CodeTorso** [comment]
> > Wait... How serious is this project ??
> 
> This GitHub Organization is exclusively dedicated to open source projects and contributors.
> 
> It is officially affiliated with the Google Developer Student Club at GEU. You can find more information about the organization on our LinkedIn page: - [ ] https://www.linkedin.com/company/dscgeu/
> 
> As a side note, I am currently serving as the lead for open source projects at GDSC GEU.
> 
> While our GitHub Organization's repository& LinkedIn page may appear inactive at the moment, this is because we haven't yet introduced it to our students. However, rest assured, we are planning to roll it out to our students within this month.
> 
> Please note that the current inactivity should not be taken as a measure of the project's seriousness or potential. It is simply a preliminary phase before the official introduction and kick-off. Once it's introduced to the students, you can expect to see a surge in activity as our students start contributing to the open source projects.

Is this written by AI. I just checked for AI content detection and it says 90% chance

**Comment by AdarshRawat1** [comment]
> Is this written by AI. I just checked for AI content detection and it says 90% chance

It wasn't generated/written by AI, but I'll consider that a compliment! 🥹🤣

**Comment by CodeTorso** [comment]
Your English is so formal then.

**Comment by AdarshRawat1** [comment]
@bilalshaikh292 I'll be closing this PR. Kindly sync your fork with 'main' branch and then reopen a PR.

**Comment by AdarshRawat1** [comment]
> Your English is so formal then.

Will work on it 🧑‍💻

**Pull request closed without merging**
