### PR TITLE
fix: denied user request to change textarea size

### PR DESCRIPTION
**Pull request by CodeTorso**
Users could easily deteriorate the entire website just by playing with message panel of contact page.

I fixed that by setting height of message panel to 8. Giving users a compatible area.

Also making sure your website integrity is maintained.

I do not believe raising issue was optimal for a 4 line of code. Just discuss here for any changes

### CODE REVIEW

**Comment by CodeTorso** [comment]
I was actually working on responsiveness as per the issue from project.

But found this thing irritating me constantly.

**Comment by CodeTorso** [comment]
we could also add only vetical sizing of textarea similar to what we have in github right here

**Comment by AdarshRawat1** [comment]
> I was actually working on responsiveness as per the issue from project.

Related to #14

**Comment by AdarshRawat1** [comment]
> we could also add only vetical sizing of textarea similar to what we have in github right here

Sure ! Sounds great . 

Mention the issue #14 in your PR making it easier to understand what you are working on .

**Comment by AdarshRawat1** [comment]
Thanks you @CodeTorso for the PR

**Comment by CodeTorso** [comment]
Nice.

**Pull request merged**
